---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnami
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.0.3
    helm:
      releaseName: wordpress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wordpress
