---
apiVersion: v1
kind: Namespace
metadata:
  name: joomla
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joomla-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: joomla
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.0.1
    helm:
      releaseName: joomla
  destination:
    server: "https://kubernetes.default.svc"
    namespace: joomla
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---