---
apiVersion: v1
kind: Namespace
metadata:
  name: mediawiki
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediawiki-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mediawiki
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.0.1
    helm:
      releaseName: mediawiki
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mediawiki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true