---
apiVersion: v1
kind: Namespace
metadata:
  name: odoo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: odoo
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 21.2.9
    helm:
      releaseName: odoo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: odoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true